version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: chat-app-postgres
    environment:
      POSTGRES_USER: alexsantos
      POSTGRES_PASSWORD: 7803-Aob
      POSTGRES_DB: chat-api-db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: chat-app-redis
    ports:
      - '6379:6379'

volumes:
  postgres-data:
